FILES 	= reverse.mli el.c fib.scm build.ml scm_reverse.scm
TARGET 	= test

.PHONY: all
all: build

clean:
	rm -f *.o *.zi *.sci build.scm *.lam test reverse.scm build.c *~

include ../../Makefile.camloo