(module camloo-runtime
		(import __caml_bfloat
				__caml_bint
				__caml_bio
				__caml_bmisc
				__caml_bstring
				__caml_constr
				__caml_handle
				__caml_intext
				__caml_sys
				__caml_tag
				__caml_eq
				__caml_exc
				__caml_list
				__caml_int
				__caml_fstring
				__caml_fchar
				__caml_string
				__caml_char
				__caml_fvect
				__caml_vect
				__caml_filename
				__caml_float
				__caml_pair
				__caml_random
				__caml_baltree
				__caml_map
				__caml_stack
				__caml_set
				__caml_sort
				__caml_queue
				__caml_io
				__caml_arg
				__caml_stream
				__caml_printf
				__caml_printexc
				__caml_hashtbl
				__caml_lexing
				__caml_genlex
				__caml_parsing)
		(eval (export-all)))
