(* Dummy interface file for caml-light -> hop compilation *)

(* define a new global service *)
value define_service : string -> ('a -> 'b) -> unit;;

(* Basic HTML functions (would need to be autogenerated later - with optional labels ideally *)
value html : string list -> string;;
value body : string list -> string;;
